inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'spec/spec_helper.rb'
    - 'app/assets/node_modules/**/*'

Style/Documentation:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 80

Metrics/AbcSize:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
